<a href="https://colab.research.google.com/github/Debabrat1/Machine_Learning_Codes/blob/main/ML_LAB_ASSIGNMENT_1(Debabrat_Sarma_ECE).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Part 1: Python Basic
# 1. Write a command to get the python version you are using.
!python3 --version

Python 3.6.9


In [ ]:
# 2. Write a command or program to locate python site-packages.
import site;
print(site.getsitepackages())

['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']


In [ ]:
# 3. Write a command or program to get the path and name of the file that is currently executing.
import sys
print(sys.argv[0])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py


In [ ]:
# 4. Write a python program to randomly generate two matrices of size[2x3 and 3x2] and do the matrix multiplication using the two generated matrices.(Say A=BC)
import numpy as np
np.random.seed(42)
B= np.random.randint(0, 15, size=(2,3))
C= np.random.randint(0, 15, size=(3,2))
print("Matrix B:\n", B)
print("Shape of B=", B.shape)
print()
print("Matrix C:\n", C)
print("Shape of C=", C.shape)
A= np.matmul(B, C)
print()
print("Product of B and C:\n", A)
print("Shape of product=", A.shape)

Matrix B:
 [[ 6  3 12]
 [14 10  7]]
Shape of B= (2, 3)

Matrix C:
 [[12  4]
 [ 6  9]
 [ 2  6]]
Shape of C= (3, 2)

Product of B and C:
 [[114 123]
 [242 188]]
Shape of product= (2, 2)


In [ ]:
# 5. Use a for loop to implement the above question five times and thereafter take the average of all the five matrices and display the result.
import numpy as np
for A in range(5):
  print([[114,123],[242,188]])
  data=[[114, 123],[242, 188]]
  [[114, 123], [242, 188]]
  [[114, 123], [242, 188]]
  [[114, 123], [242, 188]]
  [[114, 123], [242, 188]]
  print("\nAverage of matrices are, axis= None:", np.mean(data))

[[114, 123], [242, 188]]

Average of matrices are, axis= None: 166.75
[[114, 123], [242, 188]]

Average of matrices are, axis= None: 166.75
[[114, 123], [242, 188]]

Average of matrices are, axis= None: 166.75
[[114, 123], [242, 188]]

Average of matrices are, axis= None: 166.75
[[114, 123], [242, 188]]

Average of matrices are, axis= None: 166.75


In [ ]:
# 6. Write a program to transfer the matrix(generated in question 5) to the CSV file and then read the same matrix and display the transpostion of it.
import numpy
import pandas
import csv
a=numpy.array([[1, 6, 4], [2, 4, 8], [3, 9, 1]])
numpy.savetxt("data3.csv",a,delimiter=",")
df=pandas.read_csv('data3.csv')
print(df)
matrix_transpose=df.transpose()
print()
print("Transpose of the Matrix is=", matrix_transpose)

   1.000000000000000000e+00  6.000000000000000000e+00  4.000000000000000000e+00
0                       2.0                       4.0                       8.0
1                       3.0                       9.0                       1.0

Transpose of the Matrix is=                             0    1
1.000000000000000000e+00  2.0  3.0
6.000000000000000000e+00  4.0  9.0
4.000000000000000000e+00  8.0  1.0


In [ ]:
# 7. Write a program to find the mean,mode,and median of the above-mentioned matrix.
import numpy
from scipy import stats
a= numpy.array([[1, 6, 4], [2, 4, 8], [3, 9, 1]])
x= numpy.mean(a)
y=numpy.median(a)
z=stats.mode(a)
print("The Mean is=", x)
print("The Median is=", y)
print("The Mode is=", z)

The Mean is= 4.222222222222222
The Median is= 4.0
The Mode is= ModeResult(mode=array([[1, 4, 1]]), count=array([[1, 1, 1]]))


In [ ]:
# 8. Write a program to print the upper triangle of the matrix.
a=[[2, 3, 9], [11, 1, 8], [3, 5, 13]];
l= len(a)
m= len(a[0])
if(l !=m):
  print("Matrix should be a square matrix");
else:
    print("Upper triangular matrix: ");
    for i in range(0, l):
      for j in range(0, m):
        if(i>j):
          print("0"),
        else:
            print(a[i][j]),

      print(" ");

Upper triangular matrix: 
2
3
9
 
0
1
8
 
0
0
13
 


In [ ]:
# 9. Write a Python program to read specific columns of a given CSV file and print the content of the columns. (Column number should be given by the user)
import csv
with open('Players.csv', newline='') as csvfile:
  data=csv.DictReader(csvfile)
  print("surname team porition minutes shots passes tackles saves")
  print("--------------------------------------------------------")
  for row in data:
    print(row['surname'], row['team'])

In [ ]:
# 10. Write a Python program to replace a user-defined number present in the CSV file by the character 'A'.
import csv
text=open("Players.csv", "r")

#join() method combines all contents of csvfile.csv and formed as a string
text=''.join([i for i in text])

#search and replace the contents
text=text.replace("16", "A")

# output.csv is the output file opened in write mode
x= open("output.csv","w")

# all the replaced text is written in the output.csv file
x.writelines(text)
x.close()

In [ ]:
# Part 2: Numpy Basic
# 1. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
import numpy as np
array= np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# 2. Write a NumPy program to create an array of all the even integers from 10 to 50.
import numpy as np
array=np.arange(10,51,2)
print("Array of all the even integers from 10 to 50")
print(array)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# 3. Write a NumPy program to generate a random number between 0 and 1
import numpy as np
rand_num=np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.54256004]


In [ ]:
# 4. Write a NumPy program to save the matrix (generated in question 3) to a text file and load it
import numpy as np
import os
x= np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header= 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header)
print("After loading, content of the text file:")
result= np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
# Part 3: Pandas Excel
# 1. Write a python program to read an image and save the image as a matrix to a .csv file using pandas
import numpy as np
import matplotlib.image as img
import pandas as pd


imageMat= img.imread('2.jpg')
print("Image shape:",imageMat.shape)

# if image is colored (RGB)
if(imageMat.shape[2]==3):

  # reshape it from 3D matrices to 2D matrice
  imageMat_reshape= imageMat.reshape(imageMat.shape[0],-1)

  print("Reshaping to 2D array:",imageMat_reshape.shape)

 # if image is grayscale
 else:
   # remain as it is
   imageMat_reshape= imageMat

   # converting it to dataframe.
   mat_df=pd.DataFrame(imageMat_reshape)

   # exporting dataframe to csv file
   mat_df.to_csv('imageoutput.csv',header= None, index= None)

   # retrieving dataframe from CSV file
   loaded_df=pd.read_csv('imageoutput.csv',sep',', header= None)

   # getting matrice values.
   loaded_2D_mat= loaded_df.values

   # reshaping it to 3D matrice 
   loaded_mat= laoded_2D_mat.reshape(loaded_2D_mat.shape[0], loaded_2D_mat.shape[1]// imageMat.shape[2],imageMat.shape[2])
   
   print("Image shape of loaded Image:", loaded_mat.shape)

   # check if both matrice have same shape or not
   if((imageMat== loaded_mat).all()):
     print("\n\nYes"," The loaded matrice from CSV file is same as original image matrice")

In [ ]:
# 2. Write a program to import excel data from the .csv file(generated in question 1 by excluding the last row and last column)
import pandas as pd

df= pd.read_csv(r'imageoutput.csv')
print(df)

#delete last column
df= df[df.columns[:-1]]

#delete last row
df.drop(df.tail(1).index,inplace=True)

print("After removing last column and row")
print(df)

In [ ]:
# 3. Write a Pandas program to create the today's date
import pandas as pd
from datetime import date
now=pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-01-14 00:00:00


In [ ]:
# Part 4
# 1. Create a mini calculator to know the age of a person after putting the range(i.e. date of birth and current date)
from datetime import date

def calculateAge(birthDate):
  days_in_year=365.2425
  age= int((date.today()- birthDate).days/ days_in_year)
  return age

print(calculateAge(date(1995, 3, 4)), "years")

25 years
